/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kuai_shou_ad_go

import (
	"github.com/wenxtech/kuai_shou_ad_go/api"
	"github.com/wenxtech/kuai_shou_ad_go/middleware"
)

type Client struct {
	ApiClient *api.APIClient
}

func Init(cfg *api.Configuration) *Client {
	client := &Client{
		ApiClient: api.NewAPIClient(cfg),
	}
	client.ApiClient.Use(
		middleware.AuthMiddleware,
		middleware.HeaderMiddleware,
		middleware.LogMiddleware,
	)
	return client
}
// API Services
func (c *Client) Oauth2AuthorizeAccessTokenAPI() *api.Oauth2AuthorizeAccessTokenAPIService {
	return c.ApiClient.Oauth2AuthorizeAccessTokenAPI
}
func (c *Client) Oauth2AuthorizeRefreshTokenAPI() *api.Oauth2AuthorizeRefreshTokenAPIService {
	return c.ApiClient.Oauth2AuthorizeRefreshTokenAPI
}
func (c *Client) V1AsyncTaskCreateAPI() *api.V1AsyncTaskCreateAPIService {
	return c.ApiClient.V1AsyncTaskCreateAPI
}
func (c *Client) V1AsyncTaskDownloadAPI() *api.V1AsyncTaskDownloadAPIService {
	return c.ApiClient.V1AsyncTaskDownloadAPI
}
func (c *Client) V1AsyncTaskListAPI() *api.V1AsyncTaskListAPIService {
	return c.ApiClient.V1AsyncTaskListAPI
}
func (c *Client) V1ReportAccountReportAPI() *api.V1ReportAccountReportAPIService {
	return c.ApiClient.V1ReportAccountReportAPI
}
func (c *Client) V1ReportCampaignReportAPI() *api.V1ReportCampaignReportAPIService {
	return c.ApiClient.V1ReportCampaignReportAPI
}
func (c *Client) V1ReportCreativeReportAPI() *api.V1ReportCreativeReportAPIService {
	return c.ApiClient.V1ReportCreativeReportAPI
}
func (c *Client) V1ReportMaterialReportAPI() *api.V1ReportMaterialReportAPIService {
	return c.ApiClient.V1ReportMaterialReportAPI
}
func (c *Client) V1ReportUnitReportAPI() *api.V1ReportUnitReportAPIService {
	return c.ApiClient.V1ReportUnitReportAPI
}

func (c *Client) CommonApi() *api.CommonApiService {
	return c.ApiClient.CommonApi
}

func (c *Client) SetHost(host string) {
	c.ApiClient.Cfg.Host = host
}

func (c *Client) Use(mws ...api.Middleware) {
	c.ApiClient.Use(mws...)
}

func (c *Client) AddDefaultHeader(key string, value string) {
	c.ApiClient.Cfg.AddDefaultHeader(key, value)
}

func (c *Client) SetDebug(enable bool) {
	c.ApiClient.Cfg.Debug = enable
}