/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
    . "github.com/wenxtech/kuai_shou_ad_go/models"
)


// V1AsyncTaskDownloadAPIService V1AsyncTaskDownloadAPI service
type V1AsyncTaskDownloadAPIService service

type ApiV1AsyncTaskDownloadGetRequest struct {
	ctx context.Context
	ApiService *V1AsyncTaskDownloadAPIService
	v1AsyncTaskDownloadGetRequest *V1AsyncTaskDownloadGetRequest
}

func (r *ApiV1AsyncTaskDownloadGetRequest) V1AsyncTaskDownloadGetRequest(v1AsyncTaskDownloadGetRequest V1AsyncTaskDownloadGetRequest) *ApiV1AsyncTaskDownloadGetRequest {
	r.v1AsyncTaskDownloadGetRequest = &v1AsyncTaskDownloadGetRequest
	return r
}

func (r *ApiV1AsyncTaskDownloadGetRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.buildExecute(r)
}

func (r *ApiV1AsyncTaskDownloadGetRequest) WithLog(enable bool) *ApiV1AsyncTaskDownloadGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, ContextEnableLog, true)
	}
	return r
}

/*
V1AsyncTaskDownloadGet 数据下载



 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1AsyncTaskDownloadGetRequest
*/
func (a *V1AsyncTaskDownloadAPIService) Get(ctx context.Context) *ApiV1AsyncTaskDownloadGetRequest {
	return &ApiV1AsyncTaskDownloadGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *V1AsyncTaskDownloadAPIService) buildExecute(r *ApiV1AsyncTaskDownloadGetRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []FormFile
		localVarReturnValue  map[string]interface{}
	)
	
	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath, err := a.client.Cfg.ServerURLWithContext(r.ctx, "V1AsyncTaskDownloadAPIService.V1AsyncTaskDownloadGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/async_task/download"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.v1AsyncTaskDownloadGetRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(r.ctx, req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
