/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
    . "github.com/wenxtech/kuai_shou_ad_go/models"
)


// Oauth2AuthorizeAccessTokenAPIService Oauth2AuthorizeAccessTokenAPI service
type Oauth2AuthorizeAccessTokenAPIService service

type ApiOauth2AuthorizeAccessTokenPostRequest struct {
	ctx context.Context
	ApiService *Oauth2AuthorizeAccessTokenAPIService
	oauth2AuthorizeAccessTokenPostRequest *Oauth2AuthorizeAccessTokenPostRequest
}

func (r *ApiOauth2AuthorizeAccessTokenPostRequest) Oauth2AuthorizeAccessTokenPostRequest(oauth2AuthorizeAccessTokenPostRequest Oauth2AuthorizeAccessTokenPostRequest) *ApiOauth2AuthorizeAccessTokenPostRequest {
	r.oauth2AuthorizeAccessTokenPostRequest = &oauth2AuthorizeAccessTokenPostRequest
	return r
}

func (r *ApiOauth2AuthorizeAccessTokenPostRequest) Execute() (*Oauth2AuthorizeAccessTokenResponse, *http.Response, error) {
	return r.ApiService.buildExecute(r)
}

func (r *ApiOauth2AuthorizeAccessTokenPostRequest) WithLog(enable bool) *ApiOauth2AuthorizeAccessTokenPostRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, ContextEnableLog, true)
	}
	return r
}

/*
Oauth2AuthorizeAccessTokenPost 获取 token



 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiOauth2AuthorizeAccessTokenPostRequest
*/
func (a *Oauth2AuthorizeAccessTokenAPIService) Post(ctx context.Context) *ApiOauth2AuthorizeAccessTokenPostRequest {
	return &ApiOauth2AuthorizeAccessTokenPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return Oauth2AuthorizeAccessTokenResponse
func (a *Oauth2AuthorizeAccessTokenAPIService) buildExecute(r *ApiOauth2AuthorizeAccessTokenPostRequest) (*Oauth2AuthorizeAccessTokenResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []FormFile
		localVarReturnValue  *Oauth2AuthorizeAccessTokenResponse
	)
	
	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath, err := a.client.Cfg.ServerURLWithContext(r.ctx, "Oauth2AuthorizeAccessTokenAPIService.Oauth2AuthorizeAccessTokenPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/oauth2/authorize/access_token"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.oauth2AuthorizeAccessTokenPostRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(r.ctx, req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
