/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspUnitListResponseDataDetailsInnerAdvCardListInner struct for GwDspUnitListResponseDataDetailsInnerAdvCardListInner
type GwDspUnitListResponseDataDetailsInnerAdvCardListInner struct {
	AdvCardId *int64 `json:"adv_card_id,omitempty"`
	CardType *int64 `json:"card_type,omitempty"`
	Price *int64 `json:"price,omitempty"`
	SalePrice *int64 `json:"sale_price,omitempty"`
	SdpaCardContent *string `json:"sdpa_card_content,omitempty"`
	Subtitle *string `json:"subtitle,omitempty"`
	Title *string `json:"title,omitempty"`
	Url *string `json:"url,omitempty"`
}


