/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// Oauth2AuthorizeRefreshTokenPostRequest struct for Oauth2AuthorizeRefreshTokenPostRequest
type Oauth2AuthorizeRefreshTokenPostRequest struct {
	// 申请应用后快手返回的 app_id
	AppId int64 `json:"app_id"`
	// 申请应用后快手返回的 secret
	Secret string `json:"secret"`
	// 最近一次快手返回的 refresh_token
	RefreshToken string `json:"refresh_token"`
}

type _Oauth2AuthorizeRefreshTokenPostRequest Oauth2AuthorizeRefreshTokenPostRequest


