/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// V1AsyncTaskDownloadGetRequest struct for V1AsyncTaskDownloadGetRequest
type V1AsyncTaskDownloadGetRequest struct {
	// 广告主 ID（注：非账户快手 ID），在获取 accessToken 时返回
	AdvertiserId string `json:"advertiser_id"`
	// 任务 ID
	TaskId string `json:"task_id"`
}

type _V1AsyncTaskDownloadGetRequest V1AsyncTaskDownloadGetRequest


