/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspUnitListResponseDataDetailsInnerCustomMiniAppData struct for GwDspUnitListResponseDataDetailsInnerCustomMiniAppData
type GwDspUnitListResponseDataDetailsInnerCustomMiniAppData struct {
	BootstrapPage *string `json:"bootstrap_page,omitempty"`
	BootstrapParams *string `json:"bootstrap_params,omitempty"`
	MiniAppIdPlatform *string `json:"mini_app_id_platform,omitempty"`
	MiniAppType *string `json:"mini_app_type,omitempty"`
}


