/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// V1ReportUnitReportResponse struct for V1ReportUnitReportResponse
type V1ReportUnitReportResponse struct {
	Code int64 `json:"code"`
	Data V1ReportUnitReportResponseData `json:"data"`
	Message string `json:"message"`
	RequestId string `json:"request_id"`
}

type _V1ReportUnitReportResponse V1ReportUnitReportResponse


