/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspUnitListResponse struct for GwDspUnitListResponse
type GwDspUnitListResponse struct {
	Code int64 `json:"code"`
	Data GwDspUnitListResponseData `json:"data"`
	Message string `json:"message"`
	RequestId string `json:"request_id"`
}

type _GwDspUnitListResponse GwDspUnitListResponse


