/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// Oauth2AuthorizeAccessTokenPostRequest struct for Oauth2AuthorizeAccessTokenPostRequest
type Oauth2AuthorizeAccessTokenPostRequest struct {
	// 申请应用后快手返回的 app_id
	AppId int64 `json:"app_id"`
	// 申请应用后快手返回的 secret
	Secret string `json:"secret"`
	// 授权时返回的 auth_code
	AuthCode string `json:"auth_code"`
}

type _Oauth2AuthorizeAccessTokenPostRequest Oauth2AuthorizeAccessTokenPostRequest


