/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspUnitListGetRequest struct for GwDspUnitListGetRequest
type GwDspUnitListGetRequest struct {
	// 广告主id
	AdvertiserId int64 `json:"advertiser_id"`
	// 请求的页码数 默认为 1
	Page int64 `json:"page"`
	// 请求的每页行数 默认为 20
	PageSize int64 `json:"page_size"`
	// 广告计划 ID
	CampaignId *int64 `json:"campaign_id,omitempty"`
	// 广告计划类型
	CampaignType *int64 `json:"campaign_type,omitempty"`
	// 广告组 ID
	UnitId *int64 `json:"unit_id,omitempty"`
	// 广告组 ID 集 不超过 100 个
	UnitIds []int64 `json:"unit_ids,omitempty"`
	// 广告组名称
	UnitName *string `json:"unit_name,omitempty"`
	// 1.如传入此字段时不传\"start_date\"，与\"end_date\"字段，则不根据时间筛选。2.传入\"start_date\"，与\"end_date\"字段，且此字段为 1 时，按照创建时间进行筛选。3.传入\"start_date\"，与\"end_date\"字段，此字段不传，或传值为 0 时，则按照更新时间进行筛选
	TimeFilterType *int64 `json:"time_filter_type,omitempty"`
	// 开始时间 格式为\"yyyy-MM-dd\"
	EndDate *string `json:"end_date,omitempty"`
	// 结束时间 格式为\"yyyy-MM-dd\"
	StartDate *string `json:"start_date,omitempty"`
	// 应用名称
	AppName *string `json:"app_name,omitempty"`
	// 深度转化类型
	DeepConversionTypeList []string `json:"deep_conversion_type_list,omitempty"`
	// 请补充描述详情
	OcpxActionTypeList []string `json:"ocpx_action_type_list,omitempty"`
	// 单元投放状态筛选 1：投放；2：暂停；3：删除
	PutStatusList []string `json:"put_status_list,omitempty"`
	// 单元审核状态筛选 1：待审核；2：审核通过；3：审核失败；7：待送审
	ReviewStatusList []string `json:"review_status_list,omitempty"`
	// 广告组状态 -2：不限(已删除)；10：广告组已删除；40：广告创意已删除.所有不包含已删除 其他值无效
	Status *int64 `json:"status,omitempty"`
}

type _GwDspUnitListGetRequest GwDspUnitListGetRequest


