/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspUnitListResponseDataDetailsInnerSeriesCardInfo struct for GwDspUnitListResponseDataDetailsInnerSeriesCardInfo
type GwDspUnitListResponseDataDetailsInnerSeriesCardInfo struct {
	PicId *int64 `json:"pic_id,omitempty"`
	Description *string `json:"description,omitempty"`
	CoverImage *string `json:"cover_image,omitempty"`
	Label []string `json:"label,omitempty"`
	Title *string `json:"title,omitempty"`
}


