/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// V1ReportAccountReportPostRequest struct for V1ReportAccountReportPostRequest
type V1ReportAccountReportPostRequest struct {
	// 广告主 ID（注：非账户快手 ID），在获取 accessToken 时返回
	AdvertiserId int64 `json:"advertiser_id"`
	// 过滤筛选条件，格式 yyyy-MM-dd 可选时间范围参见文档上方说明
	StartDate string `json:"start_date"`
	// 过滤筛选条件，格式 yyyy-MM-dd 可选时间范围参见文档上方说明
	EndDate string `json:"end_date"`
	// 请求的页码，默认为 1
	Page int64 `json:"page"`
	// 每页行数，默认为 20，最大支持 2000
	PageSize int64 `json:"page_size"`
	// 天粒度（DAILY）／小时粒度（HOURLY），默认支持天粒度数据
	TemporalGranularity *string `json:"temporal_granularity,omitempty"`
}

type _V1ReportAccountReportPostRequest V1ReportAccountReportPostRequest


