/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// V1AsyncTaskCreateResponseData struct for V1AsyncTaskCreateResponseData
type V1AsyncTaskCreateResponseData struct {
	AdvertiserId int64 `json:"advertiser_id"`
	TaskId int64 `json:"task_id"`
}

type _V1AsyncTaskCreateResponseData V1AsyncTaskCreateResponseData


