/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// V1ReportMaterialReportPostRequest struct for V1ReportMaterialReportPostRequest
type V1ReportMaterialReportPostRequest struct {
	// 广告主 ID（注：非账户快手 ID），在获取 accessToken 时返回
	AdvertiserId int64 `json:"advertiser_id"`
	// 过滤筛选条件，格式 yyyy-MM-dd 可选时间范围参见文档上方说明
	StartDate string `json:"start_date"`
	// 过滤筛选条件，格式 yyyy-MM-dd 可选时间范围参见文档上方说明
	EndDate string `json:"end_date"`
	// 请求的页码，默认为 1
	Page int64 `json:"page"`
	// 每页行数，默认为 20，最大支持 1000
	PageSize int64 `json:"page_size"`
	// 报表类型：5 - 视频报表 7 - 封面报表 8 - 便利贴报表;16-图片报表；
	ViewType string `json:"view_type"`
	// 天粒度（DAILY）／小时粒度（HOURLY），默认支持天粒度数据
	TemporalGranularity *string `json:"temporal_granularity,omitempty"`
	// 计划类型，过滤筛选条件 1 - 作品推广；2 - 提升应用安装；3 - 获取电商下单；4 - 推广品牌活动；5 - 收集销售线索；6 - 保量广告；7 - 提高应用活跃。
	CampaignType *int64 `json:"campaign_type,omitempty"`
	// 广告计划 ID 集，过滤筛选条件，单次查询数量不超过 5000
	CampaignIds []int64 `json:"campaign_ids,omitempty"`
	// 广告组 ID 集，过滤筛选条件，单次查询数量不超过 5000
	UnitIds []int64 `json:"unit_ids,omitempty"`
	// 广告创意 ID 集，过滤筛选条件，单次查询数量不超过 5000
	CreativeIds []int64 `json:"creative_ids,omitempty"`
	// 视频 ID 集，过滤筛选条件，单次查询数量不超过 5000
	PhotoIds []int64 `json:"photo_ids,omitempty"`
	// 封面 ID 集，过滤筛选条件，单次查询数量不超过 5000
	CoverIds []int64 `json:"cover_ids,omitempty"`
	// 素材类型：1 - 竖版视频; 2 - 横版视频; 3 - 便利贴;5 -竖版图片; 6- 横版图片; 9-小图；10-组图
	CreativeMaterialType *int64 `json:"creative_material_type,omitempty"`
}

type _V1ReportMaterialReportPostRequest V1ReportMaterialReportPostRequest


