/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspUnitListResponseDataDetailsInner struct for GwDspUnitListResponseDataDetailsInner
type GwDspUnitListResponseDataDetailsInner struct {
	AssetMining *bool `json:"asset_mining,omitempty"`
	SiteType *int64 `json:"site_type,omitempty"`
	AdType *int64 `json:"ad_type,omitempty"`
	DpaDynamicParamsForUri *string `json:"dpa_dynamic_params_for_uri,omitempty"`
	SchemaUri *string `json:"schema_uri,omitempty"`
	ProductImage *string `json:"product_image,omitempty"`
	PackageId *int64 `json:"package_id,omitempty"`
	BidType *int64 `json:"bid_type,omitempty"`
	ProductPrice *float64 `json:"product_price,omitempty"`
	PutStatus *int64 `json:"put_status,omitempty"`
	SmartCover *bool `json:"smart_cover,omitempty"`
	DpaOuterIds []string `json:"dpa_outer_ids,omitempty"`
	DpaUnitSubType *int64 `json:"dpa_unit_sub_type,omitempty"`
	ULink *string `json:"u_link,omitempty"`
	AppStore []string `json:"app_store,omitempty"`
	AppDownloadType *int64 `json:"app_download_type,omitempty"`
	DspVersion *int64 `json:"dsp_version,omitempty"`
	PlayableId *int64 `json:"playable_id,omitempty"`
	EpisodeId *int64 `json:"episode_id,omitempty"`
	PlayableSwitch *int64 `json:"playable_switch,omitempty"`
	ProductId *string `json:"product_id,omitempty"`
	SchemaId *string `json:"schema_id,omitempty"`
	UnitSource *int64 `json:"unit_source,omitempty"`
	SeriesPayTemplateId *int64 `json:"series_pay_template_id,omitempty"`
	AppId *int64 `json:"app_id,omitempty"`
	CampaignId *int64 `json:"campaign_id,omitempty"`
	DayBudget *int64 `json:"day_budget,omitempty"`
	OcpxActionType *int64 `json:"ocpx_action_type,omitempty"`
	UseAppMarket *int64 `json:"use_app_market,omitempty"`
	TargetExplore *int64 `json:"target_explore,omitempty"`
	ComponentId *int64 `json:"component_id,omitempty"`
	DpaDynamicParams *int64 `json:"dpa_dynamic_params,omitempty"`
	CreateTime *string `json:"create_time,omitempty"`
	PlayButton *string `json:"play_button,omitempty"`
	UrlType *int64 `json:"url_type,omitempty"`
	SupportUnitIds []string `json:"support_unit_ids,omitempty"`
	DpaCategories []string `json:"dpa_categories,omitempty"`
	ProductName *string `json:"product_name,omitempty"`
	SeriesPayMode *int64 `json:"series_pay_mode,omitempty"`
	ShowMode *int64 `json:"show_mode,omitempty"`
	UnitName *string `json:"unit_name,omitempty"`
	ExtendSearch *bool `json:"extend_search,omitempty"`
	QuickSearch *int64 `json:"quick_search,omitempty"`
	SiteId *int64 `json:"site_id,omitempty"`
	SeriesCardInfo *GwDspUnitListResponseDataDetailsInnerSeriesCardInfo `json:"series_card_info,omitempty"`
	DayBudgetSchedule []string `json:"day_budget_schedule,omitempty"`
	Status *int64 `json:"status,omitempty"`
	ConsultId *int64 `json:"consult_id,omitempty"`
	RoiRatio *int64 `json:"roi_ratio,omitempty"`
	LiveComponentType *int64 `json:"live_component_type,omitempty"`
	EnhanceConversionType *int64 `json:"enhance_conversion_type,omitempty"`
	UnitType *int64 `json:"unit_type,omitempty"`
	OuterId *string `json:"outer_id,omitempty"`
	StudyStatus *int64 `json:"study_status,omitempty"`
	SeriesCardType *int64 `json:"series_card_type,omitempty"`
	CustomMiniAppData *GwDspUnitListResponseDataDetailsInnerCustomMiniAppData `json:"custom_mini_app_data,omitempty"`
	UpdateTime *string `json:"update_time,omitempty"`
	ImMessageMount *bool `json:"im_message_mount,omitempty"`
	LibraryId *int64 `json:"library_id,omitempty"`
	DeepConversionType *int64 `json:"deep_conversion_type,omitempty"`
	DeepConversionBid *int64 `json:"deep_conversion_bid,omitempty"`
	KwaiBookId *int64 `json:"kwai_book_id,omitempty"`
	DpaDynamicParamsForDp *string `json:"dpa_dynamic_params_for_dp,omitempty"`
	UnitId *int64 `json:"unit_id,omitempty"`
	PageAuditStatus *int64 `json:"page_audit_status,omitempty"`
	JingleBellId *int64 `json:"jingle_bell_id,omitempty"`
	LiveUserId *int64 `json:"live_user_id,omitempty"`
	PlayableUrl *string `json:"playable_url,omitempty"`
	PlayableFileName *string `json:"playable_file_name,omitempty"`
	WebUriType *int64 `json:"web_uri_type,omitempty"`
	ReviewDetail *string `json:"review_detail,omitempty"`
	EndTime *string `json:"end_time,omitempty"`
	CompensateStatus *int64 `json:"compensate_status,omitempty"`
	SceneId []int64 `json:"scene_id,omitempty"`
	BeginTime *string `json:"begin_time,omitempty"`
	UnitMaterialType *int64 `json:"unit_material_type,omitempty"`
	ConvertId *int64 `json:"convert_id,omitempty"`
	Url *string `json:"url,omitempty"`
	Target *GwDspUnitListResponseDataDetailsInnerTarget `json:"target,omitempty"`
	SeriesId *int64 `json:"series_id,omitempty"`
	ScheduleTime *string `json:"schedule_time,omitempty"`
	AdvCardList []GwDspUnitListResponseDataDetailsInnerAdvCardListInner `json:"adv_card_list,omitempty"`
	OuterLoopNative *int64 `json:"outer_loop_native,omitempty"`
	CpaBid *int64 `json:"cpa_bid,omitempty"`
	PlayableOrientation *int64 `json:"playable_orientation,omitempty"`
	TemplateId *int64 `json:"template_id,omitempty"`
	Bid *int64 `json:"bid,omitempty"`
	AdvCardOption *int64 `json:"adv_card_option,omitempty"`
}


