/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// V1AsyncTaskCreatePostRequestTaskParams 报表任务参数，详见下方
type V1AsyncTaskCreatePostRequestTaskParams struct {
	// 格式如：yyyy-MM-dd，时间跨度不能超过 6 个月
	StartDate string `json:"start_date"`
	// 格式如：yyyy-MM-dd，不大于查询开始日期
	EndDate string `json:"end_date"`
	// 1：账户维度查询，2: 广告计划维度查询，3：广告组维度查询，4：广告创意维度查询(自定义创意) 5：视频报表 报表 7：封面报表 8：便利贴报表 10：程序化创意 2.0 报表 21：关键词报表 25：搜索词报表
	ViewType int64 `json:"view_type"`
	// 推广关键词ID集，过滤筛选条件，单次查询数量不超过 5000,推广关键词ID集可通过获取关键词列表接口获取
	Query []string `json:"query"`
	// “DAILY”：天粒度；“HOURLY”：小时粒度；默认按天粒度进行聚合
	TemporalGranularity *string `json:"temporal_granularity,omitempty"`
	// 广告计划 ID 集，过滤筛选条件，单次查询数量不超过 5000
	CampaignIds []int64 `json:"campaign_ids,omitempty"`
	// 广告组 ID 集，过滤筛选条件，单次查询数量不超过 5000
	UnitIds []int64 `json:"unit_ids,omitempty"`
	// 广告创意 ID 集，过滤筛选条件，单次查询数量不超过 5000
	CreativeIds []int64 `json:"creative_ids,omitempty"`
	// 视频 ID 集，过滤筛选条件，单次查询数量不超过 5000
	PhotoIds []int64 `json:"photo_ids,omitempty"`
	// 封面 ID 集，过滤筛选条件，单次查询数量不超过 5000
	CoverIds []int64 `json:"cover_ids,omitempty"`
}

type _V1AsyncTaskCreatePostRequestTaskParams V1AsyncTaskCreatePostRequestTaskParams


