/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// V1AsyncTaskListResponseDataDetailsInner struct for V1AsyncTaskListResponseDataDetailsInner
type V1AsyncTaskListResponseDataDetailsInner struct {
	// 广告主 ID
	AdvertiserId int64 `json:"advertiser_id"`
	// 任务 ID
	TaskId int64 `json:"task_id"`
	// 任务名称
	TaskName string `json:"task_name"`
	// 任务创建时间 格式如：yyyy-MM-dd HH:mm:ss
	CreateTime string `json:"create_time"`
	// 任务状态 0：新建，1：处理中，2：处理成功，3：处理失败
	TaskStatus int64 `json:"task_status"`
	// 文件大小 字节数
	FileSize int64 `json:"file_size"`
}

type _V1AsyncTaskListResponseDataDetailsInner V1AsyncTaskListResponseDataDetailsInner


