/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspCreativeListGetRequest struct for GwDspCreativeListGetRequest
type GwDspCreativeListGetRequest struct {
	// 广告主id
	AdvertiserId int64 `json:"advertiser_id"`
	// 请求的页码数 默认为 1
	Page int64 `json:"page"`
	// 请求的每页行数 默认为 20
	PageSize int64 `json:"page_size"`
	// 广告计划 ID
	CampaignId *int64 `json:"campaign_id,omitempty"`
	// 广告组 ID
	UnitId *int64 `json:"unit_id,omitempty"`
	// 广告创意 ID
	CreativeId *int64 `json:"creative_id,omitempty"`
	// 广告创意 ID 集
	CreativeIds []string `json:"creative_ids,omitempty"`
	// 广告创意名称
	CreativeName *string `json:"creative_name,omitempty"`
	// 1.如传入此字段时不传\"start_date\"，与\"end_date\"字段，则不根据时间筛选。2.传入\"start_date\"，与\"end_date\"字段，且此字段为 1 时，按照创建时间进行筛选。3.传入\"start_date\"，与\"end_date\"字段，此字段不传，或传值为 0 时，则按照更新时间进行筛选
	TimeFilterType *int64 `json:"time_filter_type,omitempty"`
	// 开始时间 格式为\"yyyy-MM-dd\"
	EndDate *string `json:"end_date,omitempty"`
	// 结束时间 格式为\"yyyy-MM-dd\"
	StartDate *string `json:"start_date,omitempty"`
	// 创意投放状态 筛选 1：投放；2：暂停；3：删除。备注：传了该参数会覆盖status参数筛选，因为二者是相同筛选项
	PutStatusList []string `json:"put_status_list,omitempty"`
	// 广告创意状态 -2:不限,40:只包含已删除 不传：所有不包含已删除 其他值无效
	Status *int64 `json:"status,omitempty"`
}

type _GwDspCreativeListGetRequest GwDspCreativeListGetRequest


