/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspCreativeListResponseDataDetailsInnerDisplayInfo struct for GwDspCreativeListResponseDataDetailsInnerDisplayInfo
type GwDspCreativeListResponseDataDetailsInnerDisplayInfo struct {
	ActionBarText *string `json:"action_bar_text,omitempty"`
	Description *string `json:"description,omitempty"`
}


