/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspCreativeListResponseDataDetailsInner struct for GwDspCreativeListResponseDataDetailsInner
type GwDspCreativeListResponseDataDetailsInner struct {
	CreativeName *string `json:"creative_name,omitempty"`
	AdType *int64 `json:"ad_type,omitempty"`
	AppGradeType *int64 `json:"app_grade_type,omitempty"`
	PhotoMd5 *string `json:"photo_md5,omitempty"`
	Recommendation *string `json:"recommendation,omitempty"`
	CreativeTag []string `json:"creative_tag,omitempty"`
	CoverHeight *int64 `json:"cover_height,omitempty"`
	PutStatus *int64 `json:"put_status,omitempty"`
	CreativeId *int64 `json:"creative_id,omitempty"`
	DspVersion *int64 `json:"dsp_version,omitempty"`
	OverlayBgUrl *string `json:"overlay_bg_url,omitempty"`
	MaterialIntelligentOptimize *int64 `json:"material_intelligent_optimize,omitempty"`
	CampaignId *int64 `json:"campaign_id,omitempty"`
	CreateTime *string `json:"create_time,omitempty"`
	AutoDeliverType *int64 `json:"auto_deliver_type,omitempty"`
	CreativeMode *int64 `json:"creative_mode,omitempty"`
	AdPhotoPlayedT3sUrl *string `json:"ad_photo_played_t3s_url,omitempty"`
	SplashPictures []GwDspCreativeListResponseDataDetailsInnerSplashPicturesInner `json:"splash_pictures,omitempty"`
	CoverWidth *int64 `json:"cover_width,omitempty"`
	DpaStyleTypes []string `json:"dpa_style_types,omitempty"`
	ImageToken *string `json:"image_token,omitempty"`
	MerchantProductId *string `json:"merchant_product_id,omitempty"`
	MaterialUrl []string `json:"material_url,omitempty"`
	ClickTrackUrl *string `json:"click_track_url,omitempty"`
	ActionbarClickUrl *string `json:"actionbar_click_url,omitempty"`
	MerchantLibraryId *int64 `json:"merchant_library_id,omitempty"`
	Status *int64 `json:"status,omitempty"`
	RejectVideoSnapshot []string `json:"reject_video_snapshot,omitempty"`
	KolUserId *int64 `json:"kol_user_id,omitempty"`
	OverlayBgImageToken *string `json:"overlay_bg_image_token,omitempty"`
	ExposeTag *string `json:"expose_tag,omitempty"`
	SplashPhotos []GwDspCreativeListResponseDataDetailsInnerSplashPhotosInner `json:"splash_photos,omitempty"`
	OverlayType *string `json:"overlay_type,omitempty"`
	PhotoId *string `json:"photo_id,omitempty"`
	DisplayInfo *GwDspCreativeListResponseDataDetailsInnerDisplayInfo `json:"display_info,omitempty"`
	CreativeCategory *int64 `json:"creative_category,omitempty"`
	NewExposeTag []GwDspCreativeListResponseDataDetailsInnerNewExposeTagInner `json:"new_expose_tag,omitempty"`
	UpdateTime *string `json:"update_time,omitempty"`
	LiveCreativeType *int64 `json:"live_creative_type,omitempty"`
	LiveTrackUrl *string `json:"live_track_url,omitempty"`
	DpaTemplateId *int64 `json:"dpa_template_id,omitempty"`
	UnitId *int64 `json:"unit_id,omitempty"`
	ImageTokens []string `json:"image_tokens,omitempty"`
	StickerTitle *string `json:"sticker_title,omitempty"`
	CreativeMaterialType *int64 `json:"creative_material_type,omitempty"`
	CoverUrl *string `json:"cover_url,omitempty"`
	ShortSlogan *string `json:"short_slogan,omitempty"`
	PicId *string `json:"pic_id,omitempty"`
	ReviewDetail *string `json:"review_detail,omitempty"`
	OpenAccountNative *int64 `json:"open_account_native,omitempty"`
	HighLightFlash *int64 `json:"high_light_flash,omitempty"`
	KolUserType *int64 `json:"kol_user_type,omitempty"`
	OuterLoopNative *int64 `json:"outer_loop_native,omitempty"`
	ImpressionUrl *string `json:"impression_url,omitempty"`
}


