/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspCreativeListResponseDataDetailsInnerSplashPhotosInner struct for GwDspCreativeListResponseDataDetailsInnerSplashPhotosInner
type GwDspCreativeListResponseDataDetailsInnerSplashPhotosInner struct {
	Height *int64 `json:"height,omitempty"`
	Width *int64 `json:"width,omitempty"`
	PhotoId *string `json:"photo_id,omitempty"`
	PhotoMd5 *string `json:"photo_md5,omitempty"`
}


