/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspCreativeListResponseDataDetailsInnerSplashPicturesInner struct for GwDspCreativeListResponseDataDetailsInnerSplashPicturesInner
type GwDspCreativeListResponseDataDetailsInnerSplashPicturesInner struct {
	CoverId *int64 `json:"cover_id,omitempty"`
	CoverUrl *string `json:"cover_url,omitempty"`
	Height *int64 `json:"height,omitempty"`
	KyPhotoId *int64 `json:"ky_photo_id,omitempty"`
	Width *int64 `json:"width,omitempty"`
}


