/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// V1AsyncTaskListResponseData struct for V1AsyncTaskListResponseData
type V1AsyncTaskListResponseData struct {
	// 任务总数
	TotalCount int64 `json:"total_count"`
	// 详细
	Details []V1AsyncTaskListResponseDataDetailsInner `json:"details"`
}

type _V1AsyncTaskListResponseData V1AsyncTaskListResponseData


