/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// V1AsyncTaskCreateResponse struct for V1AsyncTaskCreateResponse
type V1AsyncTaskCreateResponse struct {
	Code int64 `json:"code"`
	Message string `json:"message"`
	Data V1AsyncTaskCreateResponseData `json:"data"`
	RequestId string `json:"request_id"`
}

type _V1AsyncTaskCreateResponse V1AsyncTaskCreateResponse


