/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspUnitListResponseData struct for GwDspUnitListResponseData
type GwDspUnitListResponseData struct {
	TotalCount *int64 `json:"total_count,omitempty"`
	Details []GwDspUnitListResponseDataDetailsInner `json:"details,omitempty"`
}


