/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// Oauth2AuthorizeAccessTokenResponse struct for Oauth2AuthorizeAccessTokenResponse
type Oauth2AuthorizeAccessTokenResponse struct {
	Code int64 `json:"code"`
	Message string `json:"message"`
	Data Oauth2AuthorizeAccessTokenResponseData `json:"data"`
}

type _Oauth2AuthorizeAccessTokenResponse Oauth2AuthorizeAccessTokenResponse


