/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
    "fmt"
)
// CampaignStatus the model 'CampaignStatus'
type CampaignStatus int64

// List of CampaignStatus
const (
	CampaignStatus__1 = 1
	CampaignStatus__4 = 4
	CampaignStatus__5 = 5
	CampaignStatus__MINUS_2 = -2
)

// All allowed values of CampaignStatus enum
var AllowedCampaignStatusEnumValues = []CampaignStatus{
	1,
	4,
	5,
	-2,
}

// NewCampaignStatusFromValue returns a pointer to a valid CampaignStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCampaignStatusFromValue(v int64) (*CampaignStatus, error) {
	ev := CampaignStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CampaignStatus: valid values are %v", v, AllowedCampaignStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CampaignStatus) IsValid() bool {
	for _, existing := range AllowedCampaignStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CampaignStatus value
func (v CampaignStatus) Ptr() *CampaignStatus {
	return &v
}


