/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GwDspCreativeListResponseDataDetailsInnerNewExposeTagInner struct for GwDspCreativeListResponseDataDetailsInnerNewExposeTagInner
type GwDspCreativeListResponseDataDetailsInnerNewExposeTagInner struct {
	Text *string `json:"text,omitempty"`
	Url *string `json:"url,omitempty"`
}


