/*
磁力引擎 copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// Oauth2AuthorizeAccessTokenResponseData struct for Oauth2AuthorizeAccessTokenResponseData
type Oauth2AuthorizeAccessTokenResponseData struct {
	AccessToken string `json:"access_token"`
	RefreshTokenExpiresIn int64 `json:"refresh_token_expires_in"`
	RefreshToken string `json:"refresh_token"`
	AccessTokenExpiresIn int64 `json:"access_token_expires_in"`
}

type _Oauth2AuthorizeAccessTokenResponseData Oauth2AuthorizeAccessTokenResponseData


